name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: "~1.21"
          check-latest: true

      - name: Build
        run: |
          if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
            export VERSION=${GITHUB_REF_NAME#v}
          else
            export VERSION="$GITHUB_REF_NAME-nightly"
          fi

          LINUX_ARCHS=linux/amd64 TAGS="bindata sqlite sqlite_unlock_notify" make deps-frontend deps-backend frontend generate release-linux release-copy

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: dist/release/*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          files: dist/release/*
